name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.1

    - name: Build and functional tests
      run: ./build-and-test.sh
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ./faass
        path: ./faass
        retention-days: 1
