name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "main", "pipeline" ]
  pull_request:
    branches: [ "main", "pipeline" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.1

    - name: Build 
      run: 
        - mkdir ./cache
        - ./tests/functional-testing.py --build  --origin-path ./ --cache-path ./cache
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: faass
        path: ./faass
        retention-days: 1
