name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: GOPATH=$(pwd) go test -v 

    - name: Build
      run: GOPATH=$(pwd) go build -v -o ./faass 
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ./faass
        path: ./faass
        retention-days: 1
